/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form ventana2
     */
    public ventana2() {
        initComponents();
        ImageIcon foto = new ImageIcon("src/ventanas/imagenes/paisaje2.jpg");
        Icon pichon = new ImageIcon(foto.getImage().getScaledInstance(
        etiqueta2.getWidth(),
        etiqueta2.getHeight(), Image.SCALE_DEFAULT));
        etiqueta2.setIcon(pichon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        auno = new javax.swing.JButton();
        ayuda = new javax.swing.JButton();
        atres = new javax.swing.JButton();
        etiqueta2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        auno.setBackground(new java.awt.Color(204, 204, 255));
        auno.setForeground(new java.awt.Color(0, 0, 0));
        auno.setText("Vamos a uno");
        auno.setToolTipText("OPRIME PARA IR A VENTANA UNO");
        auno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aunoActionPerformed(evt);
            }
        });
        getContentPane().add(auno, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 223, 121, 58));

        ayuda.setBackground(new java.awt.Color(0, 102, 102));
        ayuda.setText("Ayuda");
        ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaActionPerformed(evt);
            }
        });
        getContentPane().add(ayuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 120, 60));

        atres.setBackground(new java.awt.Color(102, 255, 255));
        atres.setForeground(new java.awt.Color(0, 0, 0));
        atres.setText("Vamos a tres");
        atres.setToolTipText("OPRIME PARA IR A VENTANA TRES");
        atres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atresActionPerformed(evt);
            }
        });
        getContentPane().add(atres, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 120, 60));

        etiqueta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/imagenes/paisaje2.jpg"))); // NOI18N
        getContentPane().add(etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 730, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aunoActionPerformed
        // TODO add your handling code here:
        ventana1 ven1=new ventana1();
        ven1.setVisible(true);
        dispose();
    }//GEN-LAST:event_aunoActionPerformed

    private void ayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Estas en la ventana dos");
    }//GEN-LAST:event_ayudaActionPerformed

    private void atresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atresActionPerformed
        // TODO add your handling code here:
        ventana3 ven3=new ventana3();
        ven3.setVisible(true);
        dispose();
    }//GEN-LAST:event_atresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atres;
    private javax.swing.JButton auno;
    private javax.swing.JButton ayuda;
    private javax.swing.JLabel etiqueta2;
    // End of variables declaration//GEN-END:variables
}
